[colors]

ansi = [
  "#343f44",
  "#e67e80",
  "#a7c080",
  "#dbbc7f",
  "#7fbbb3",
  "#d699b6",
  "#83c092",
  "#d3c6aa",
]
background = "#2d353b"
brights = [
  "#5c6a72",
  "#f85552",
  "#8da101",
  "#dfa000",
  "#3a94c5",
  "#df69ba",
  "#35a77c",
  "#dfddc8",
]
cursor_bg = "#d3c6aa"
cursor_border = "#d3c6aa"
cursor_fg = "#2d353b"
foreground = "#d3c6aa"

[metadata]
name = "everforest"
origin_url = "https://github.com/Gogh-Co/Gogh"
