format = """
[](green)\
$os\
$username\
[](bg:fg0 fg:green)\
$directory\
[](fg:fg0 bg:fg4)\
$git_branch\
$git_status\
[](fg:fg4 bg:fg3)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:fg3 bg:fg2)\
$docker_context\
[](fg:fg2 bg:fg1)\
$time\
[ ](fg:fg1)\
"""


palette = "pywal"
[palettes.pywal]
fg4="#7c6f64"
fg3="#665c54"
fg2="#504945"
fg1="#3c3836"
fg0="#282828"
green="#665c54"

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:green"
style_root = "bg:#9A348E"
format = '[$user ]($style)'
disabled = false


# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#9A348E"
disabled = true # Disabled by default

[directory]
style = "bg:fg0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#57646F"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#57646F"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#57646F"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:fg4 fg:fg0"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:fg4 fg:fg0"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#57646F"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#57646F"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#57646F"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#57646F"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#57646F"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#57646F"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#57646F"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#57646F"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#57646F"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%I:%M" # Hour:Minute Format
style = "bg:fg1"
format = '[   $time ]($style)'
